# Generated by Django 3.1.1 on 2020-09-22 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageset',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
