# Generated by Django 3.1.1 on 2020-09-23 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='account_type',
            new_name='is_paid',
        ),
    ]
