# Generated by Django 3.1.1 on 2020-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200923_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
