# Generated by Django 3.1.1 on 2020-09-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fileset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileset',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
