# Generated by Django 3.1.1 on 2020-09-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fileset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileset',
            old_name='date',
            new_name='created_at',
        ),
    ]
