# Generated by Django 3.1.1 on 2020-09-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200926_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(upload_to='temp/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
