# Generated by Django 3.1.1 on 2020-09-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_temporary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporary',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
